<?php

/**
 * @file
 * Contains association.module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\FieldableEntityInterface;
use Drupal\Core\Field\FieldStorageDefinitionInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\views\ViewExecutable;
use Drupal\user\Entity\User;
use Drupal\Core\Url;

/**
 * Implements hook_help().
 */
function association_help($route_name, RouteMatchInterface $route_match)
{
  switch ($route_name) {
    // Main module help for the association module.
    case 'help.page.association':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('To manage members and persons of the association') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function association_theme()
{
  return [
    'association' => [
      'render element' => 'children',
    ],
  ];
}

function association_allowed_values_function(FieldStorageDefinitionInterface $definition, FieldableEntityInterface $entity = NULL, &$cacheable = TRUE)
{

  \Drupal::moduleHandler()->loadInclude('association', 'inc', 'association.allowed.values');

  if ($definition['entity_type'] == 'member') {
    switch ($definition['field_name']) {
      case 'country':
        return association_member_country();
        break;
      case 'status':
        return association_member_status();
        break;
      default:
        break;
    }
  }
}

function association_views_pre_render(ViewExecutable $view)
{

  switch ($view->id()) {
    case 'association_members':
      switch ($view->current_display) {
        case 'page_1':
          $view->element['#attached']['library'][] = 'association/LoM';
          break;
        default:
      }
      break;
    case 'association_persons':
      switch ($view->current_display) {
        case 'page_1':
          $view->element['#attached']['library'][] = 'association/LoP';
          break;
        default:
      }
      break;
    default:
  }

}

/**
 * Implements hook_form_alter() on behalf of association.module.
 */
function association_form_alter(&$form, FormStateInterface $form_state, $form_id)
{

  if ($form_id == 'membership') {
    $form['#attached']['library'][] = 'association/handlemembership';
  }
}

function _setListOfRecipients($status = 4)
{

  $sBcc = '';
  $database = \Drupal::database();
  $query = $database->select('member', 'am');
  $query->leftJoin('person', 'ap', 'ap.id = am.contact_id');
  $query->fields('am', ['id', 'status'])
    ->fields('ap', ['id', 'lastname', 'firstname', 'email'])
    ->condition('status', $status, '=');
  $results = $query->execute();
  foreach ($results as $key => $result) {
    $sBcc .= $result->email . ", ";
  }
  return $sBcc;

}

function association_mail($key, &$message, $aParams)
{

  $sFrom = \Drupal::config('system.site')->get('mail');

  $message['from'] = $sFrom;
  $message['headers'] = array(
    'Content-Type' => 'text/html',
    'bcc' => $aParams[0],
    'From' => $sFrom,
    'Sender' => $sFrom,
    'Return-Path' => '',
  );
  switch ($key) {
    case 'membershipfirstemail':
      $message['subject'] = '[le Jardin de Poissy] Renouvellement d\'adhésion';
      $sBody = "<b>" . $aParams[1] . "</b>";
      $message['body'][] = check_markup(nl2br($sBody), 'full_html');
      break;
    case 'membershipreminderemail':
      $message['subject'] = '[le Jardin de Poissy] Renouvellement d\'adhésion - Relance ' . $aParams[2];
      $sBody = "<b>" . $aParams[1] . "</b>";
      $message['body'][] = check_markup(nl2br($sBody), 'full_html');
      break;
  }
}

function _export_association_CSV($view, $page)
{

  $view = \Drupal\views\Views::getView($view);
  $view->setDisplay($page);
  $path = $view->getPath();

  $data = $view->preview($page)['#markup'];
  file_unmanaged_save_data($data, 'private://' . $path, FILE_EXISTS_REPLACE);

}

function association_entity_insert(EntityInterface $entity)
{
  $mode = 'insert';
  $entityType = $entity->getEntityType()->id();
  switch ($entityType) {
    case "member":
      break;
    case "person":
      break;
    default:
  }
  _export_association($entityType);
}

function association_entity_update(EntityInterface $entity)
{
  $mode = 'update';
  $entityType = $entity->getEntityType()->id();
  switch ($entityType) {
    case "member":
      if ($entity->status->value == 0) {
        // List all Persons for this Member
        $id = $entity->id->value;
        $database = \Drupal::database();
        $query = $database->select('person', 'ap');
        $query->fields('ap', ['id', 'member_id'])
          ->condition('member_id', $id, '=');
        $results = $query->execute();
        // Inactive all these Persons and the corresponding Users
        $storage = \Drupal::entityTypeManager()->getStorage('person');
        foreach ($results as $key => $result) {
          $person = $storage->load($result->id);
          $user = User::load($person->user_id->target_id);
          $person->set("isactive", 0);
          $person->set("member_id", "");
          if ($person->iscontact->value) {
            $person->set("iscontact", 0);
            $user->removeRole('contact_for_member');
          }
          $user->set("status", 0);
          $user->save();
          $person->save();
        }
      }
      break;
    case "person":
      break;
    default:
  }
  _export_association($entityType);
}

function association_entity_delete(EntityInterface $entity)
{
  $mode = 'delete';
  $entityType = $entity->getEntityType()->id();
  switch ($entityType) {
    case "member":
      break;
    case "person":
      break;
    default:
  }
  _export_association($entityType);
}

function _export_association($entityType)
{

  switch ($entityType) {
    case "member":
      _export_association_CSV('association_members', 'rest_export_1');
      break;
    case "person":
    _export_association_CSV('association_persons', 'rest_export_1');
      break;
    default:
  }
  _export_association_CSV('association_members_and_persons', 'rest_export_1');
}

function association_menu_local_tasks_alter(&$data, $route_name) {

  $oCurrentUser = \Drupal::currentUser();
  switch ($route_name) {
    case 'view.association_members_and_persons.page_1':
    case 'view.association_members.page_1':
    case 'view.association_persons.page_1':
      if ($oCurrentUser->hasPermission('administer users')) {
        $data['tabs'][0]['association.people'] = [
          '#theme' => 'menu_local_task',
          '#link' => [
            'title' => t('Users'),
            'url' => Url::fromRoute('entity.user.collection'),
          ],
          '#weight' => 4,
        ];
      }
      break;
    default:
  }

}
