<?php

/**
 * @file
 * Contains association.module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\FieldableEntityInterface;
use Drupal\Core\Field\FieldStorageDefinitionInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_help().
 */
function association_help($route_name, RouteMatchInterface $route_match)
{
  switch ($route_name) {
    // Main module help for the association module.
    case 'help.page.association':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('To manage members and persons of the association') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function association_theme()
{
  return [
    'association' => [
      'render element' => 'children',
    ],
  ];
}

function association_allowed_values_function(FieldStorageDefinitionInterface $definition, FieldableEntityInterface $entity = NULL, &$cacheable = TRUE)
{

  \Drupal::moduleHandler()->loadInclude('association', 'inc', 'association.allowed.values');

  if ($definition['entity_type'] == 'member') {
    switch ($definition['field_name']) {
      case 'country':
        return association_member_country();
        break;
      case 'status':
        return association_member_status();
        break;
      default:
        break;
    }
  }
}

function association_views_pre_render(ViewExecutable $view)
{

  switch ($view->id()) {
    case 'association_members':
      switch ($view->current_display) {
        case 'page_1':
          $view->element['#attached']['library'][] = 'association/LoM';
          break;
        default:
      }
      break;
    case 'association_persons':
      switch ($view->current_display) {
        case 'page_1':
          $view->element['#attached']['library'][] = 'association/LoP';
          break;
        default:
      }
      break;
    default:
  }

}

/**
 * Implements hook_form_alter() on behalf of association.module.
 */
function association_form_alter(&$form, FormStateInterface $form_state, $form_id)
{

  if ($form_id == 'membership') {
    $form['#attached']['library'][] = 'association/handlemembership';
  }
}

function _setListOfRecipients($status = 4)
{

  $sBcc = '';
  $database = \Drupal::database();
  $query = $database->select('member', 'am');
  $query->leftJoin('person', 'ap', 'ap.id = am.contact_id');
  $query->fields('am', ['id', 'status'])
    ->fields('ap', ['id', 'lastname', 'firstname', 'email'])
    ->condition('status', $status, '=');
  $results = $query->execute();
  foreach ($results as $key => $result) {
    $sBcc .= $result->email . ", ";
  }
  return $sBcc;

}

function association_mail($key, &$message, $aParams)
{

  $sFrom = \Drupal::config('system.site')->get('mail');

  $message['from'] = $sFrom;
  $message['headers'] = array(
    'Content-Type' => 'text/html',
    'bcc' => $aParams[0],
    'From' => $sFrom,
    'Sender' => $sFrom,
    'Return-Path' => '',
  );
  switch ($key) {
    case 'membershipfirstemail':
      $message['subject'] = '[le Jardin de Poissy] Renouvellement d\'adhésion';
      $sBody = "<b>" . $aParams[1] . "</b>";
      $message['body'][] = check_markup(nl2br($sBody), 'full_html');
      break;
    case 'membershipreminderemail':
      $message['subject'] = '[le Jardin de Poissy] Renouvellement d\'adhésion - Relance ' . $aParams[2];
      $sBody = "<b>" . $aParams[1] . "</b>";
      $message['body'][] = check_markup(nl2br($sBody), 'full_html');
      break;
  }
}

function _export_association_CSV($view, $page)
{

  $view = \Drupal\views\Views::getView($view);
  $view->setDisplay($page);
  $path = $view->getPath();

  $data = $view->preview($page)['#markup'];
  file_unmanaged_save_data($data, 'private://' . $path, FILE_EXISTS_REPLACE);

}
